package recipe;

/** This class is for menu options. */
public enum Option {
  SELECT_INGREDIENT_MENU, SELECT_RECIPE_MENU, EXIT_SYSTEM, CHECK_INGREDIENT_EXISTED, LIST_INGREDIENTS,
  SEARCH_INGREDIENT, DELETE_INGREDIENT, RETURN_START, CHECK_RECIPE_EXISTED, LIST_RECIPE, LOOK_RECIPE, DELETE_RECIPE,
  SEARCH_RECIPE, SEARCH_RECIPE_BY_INGREDIENT_NAME, SEARCH_RECIPE_BY_MAX_PRICE, SEARCH_RECIPE_BY_RECIPE_NAME,
  RETURN_RECIPE_MENU
}
